eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true #by default this is true only
    service-url:
        defaultZone: http://localhost:8761/eureka/
